# 开发 profile :连接aliyun数据库，用于开发连接用，对应禅道demo-aliyun
mysql:
  host: 39.108.12.206
  port: 3306
  qinghengHost: localhost
  qinghengPort: 8835


spring:
  datasource:
      url: jdbc:mysql://${mysql.host}:${mysql.port}/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: caodan000..
  hikari:
      data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  mvc:
    favicon:
      enabled: false




server:
    port: 8088
    address: localhost
    tomcat:
        maxHttpHeaderSize: 66665536

security:
  basic:
    enabled: false

application:
    security:
        authentication:
            jwt:
                secret: 0550224055e1848081dba46d8ad325f503fa141b
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    swagger:
        title: API
        description: API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
     #为其他系统提供的key和对应token
    smartSealBizClientConnectionPool:
#        serviceIP: localhost
#        servicePort: 8888
        serviceIP: portal.aliyun-c1.centling.cn
        servicePort: 30108
        appKey: xYUSlFxH109syg0UA8AwHSY4BmFvJI14
        appToke: xYUSlFxH109syg0UA8AwHSY4BmFvJI14
    sealToken:
        smartSealBiz:
          key: xYUSlFxH109syg0UA8AwHSY4BmFvJI14
          token: xYUSlFxH109syg0UA8AwHSY4BmFvJI14

    submail:
        msgSettingStatus: 1
        appId: 13280
        appKey: ca3ab8093095a13fed492d6097c032f7
        keyWord: 智能公章



mybatis:
    type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler


